// Generated by https://quicktype.io

export interface EstadosCiudades {
  totalResultsCount: number;
  geonames:          Geoname[];
}

export interface Geoname {
  toponymName:  string;
  name:         string;
  adminName1:   string;
}
